version: "3.8"

services:
    app:
        build: .
        ports:
            - "3000:3000"
        depends_on:
            - mongo
        environment:
            MONGO_URI: mongodb://mongo:27017/currencyDB

    mongo:
        image: mongo:8.0-rc
        restart: always
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_DATABASE=currencyDB
        volumes:
            - ./database/init.js:/docker-entrypoint-initdb.d/init.js:ro

volumes:
    mongo-data:
